services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=webapidb
      - MYSQL_USER=webapiuser
      - MYSQL_PASSWORD=webapipassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapi:
    build: api
    #restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=webApi.settings.settings
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=webapidb
      - DB_USER=webapiuser
      - DB_PASSWORD=webapipassword