# Generated by Django 2.2.9 on 2020-02-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='statusStr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='accMean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='accSd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='categoryId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='dataJSON',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='eventId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='hr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
