# Generated by Django 2.2.9 on 2020-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20200208_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='version',
            field=models.CharField(default=0.9, max_length=10),
            preserve_default=False,
        ),
    ]
