# Generated by Django 3.2.9 on 2021-11-28 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataTime', models.DateTimeField()),
                ('statusStr', models.CharField(blank=True, max_length=30, null=True)),
                ('accMean', models.FloatField(blank=True, null=True)),
                ('accSd', models.FloatField(blank=True, null=True)),
                ('hr', models.FloatField(blank=True, null=True)),
                ('categoryId', models.IntegerField(blank=True, null=True)),
                ('eventId', models.IntegerField(blank=True, null=True)),
                ('dataJSON', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
