# Generated by Django 2.2.9 on 2020-02-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20200203_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
